services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: psw123
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

 # app:
 #   build: .
 #   ports:
#    - "5000:5000"

volumes:
  db:





